### ISSUE TITLE
jQuery plugin?

### ISSUE THREAD

**Issue by froboy** [bryanbraun/after-dark-css#1]
This is, literally, the best thing. But you know what would be better than the best thing in one place? The best thing IN EVERY PLACE.

I'd love to have these as jQuery plugins so I can enhance pages with toasters or even set an actual timeout, after which the screen saver will activate. 

It's on my todo list for a little bit later. But if anyone's feeling ambitious, have at it.

**Comment by bryanbraun** [comment]
You know, you might be able to do it with something like this: https://code.google.com/p/jquery-jscreensaver/

If you could get it to display an iframe instead of just an image or video, you could just iframe in any of the standalone screensaver pages for this project (like [toasters here](http://bryanbraun.github.io/after-dark-css/all/flying-toasters.html), or [fish here](http://bryanbraun.github.io/after-dark-css/all/fish.html)).

**Comment by froboy** [comment]
With a little modification, I've got things going nicely at http://jsbin.com/pavaluwe/1/

I found that iframe-ing at 100% meant disabling the screensaver was pretty hard, so I made some tweaks to the sizing and positioning elements. It seems like 75% does nicely most places (although some of the edge-toasters are visible when the iframe is smaller).

Thanks for the tip. I'll close this up now.

**Comment by bryanbraun** [comment]
Nicely done :sunglasses:
